name: Handle Submodule Update

on:
  push:
    branches:
      - update-submodule

jobs:
  handle-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout parent repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Handle submodule update
      run: |
        # 서브모듈 업데이트를 처리하는 스크립트를 여기에 추가
        echo "Submodule updated, handling the update..."
        git submodule update --remote --merge --recursive

    - name: Merge changes to main
      run: |
        git checkout main
        git merge update-submodule
        git push origin main

    env:
      BLOG_SECRET: ${{ secrets.BLOG_SECRET }}